name: React app deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]


# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: "lts/*"
    - name: Setup Pages
      uses: actions/configure-pages@v3
    - name: Install dependencies
      run: npm install
    - name: Export
      run: npm run build
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./build

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
